version: '2'
networks:
  atran:

services:
  orderer.arnest.in:
    container_name: orderer.arnest.in
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/atran.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/arnest.in/orderers/orderer.arnest.in/:/etc/hyperledger/msp/orderer
        - ./crypto-config/peerOrganizations/atran.arnest.in/peers/peer0.atran.arnest.in/:/etc/hyperledger/msp/peeratran
    networks:
      - atran

  ca.atran.arnest.in:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.atran.arnest.in
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.atran.arnest.in-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/47733d67ed0d05c426f725827aaaf4db6b7ce86756d9528274185e53beca8fac_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/atran.arnest.in/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.atran.arnest.in
    networks:
      - atran

  peer0.atran.arnest.in:
    container_name: peer0.atran.arnest.in
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.atran.arnest.in
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=atranMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.atran.arnest.in:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=atran.arnest.couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=atran
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=p@ssw0rd
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/atran.arnest.in/peers/peer0.atran.arnest.in/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/atran.arnest.in/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.arnest.in
      - atran.arnest.couchdb
    networks:
      - atran

  atran.arnest.couchdb:
    container_name: atran.arnest.couchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=atran
      - COUCHDB_PASSWORD=p@ssw0rd
    ports:
      - 5984:5984
    networks:
      - atran

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.atran.arnest.in:7051
      - CORE_PEER_LOCALMSPID=atranMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/atran.arnest.in/users/Admin@atran.arnest.in/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
        - atran
    #depends_on:
    #  - orderer.arnest.in
    #  - peer0.atran.arnest.in
    #  - atran.arnest.couchdb
